// src/app/(site)/_components/ProductData.js

const products = [
  {
    slug: "meo-munchkin-bililac",
    name: "Mèo Munchkin chân lùn màu Bililac mã ALN3196",
    price: 350000,
    oldPrice: 450000,
    discount: 22,
    category_id: 1,
    stock: 5,
    rating: 4.8,
    reviews: 58,
    sold: 32,
    brand: "Happy Cat Farm",
    images: [
      "/images/meo/meo_anh_1.jpg",
      "/images/meo/meo_anh_1b.jpg",
      "/images/meo/meo_anh_1c.jpg",
    ],
    description:
      "Mèo Munchkin chân lùn khỏe mạnh, thuần chủng, màu bililac. Đã tiêm phòng đầy đủ, phù hợp nuôi trong căn hộ nhỏ. Tính cách hiền lành, dễ thương, rất thân thiện với trẻ em.",
    variants: ["Đực", "Cái"],
    features: [
      "Thuần chủng, giấy tờ rõ ràng",
      "Đã tiêm phòng 2 mũi",
      "Bảo hành sức khỏe 15 ngày",
    ],
    tags: ["Mèo chân lùn", "Munchkin", "Pet VIP"],
  },
  {
    slug: "meo-ald-golden",
    name: "Mèo Anh lông dài màu Golden mã ALD3094",
    price: 290000,
    oldPrice: 350000,
    discount: 17,
    category_id: 1,
    stock: 3,
    rating: 4.6,
    reviews: 42,
    sold: 21,
    brand: "Royal Cat House",
    images: [
      "/images/meo/meo_anh_2.jpg",
      "/images/meo/meo_anh_2b.jpg",
      "/images/meo/meo_anh_2c.jpg",
    ],
    description:
      "Mèo Anh lông dài màu golden sang trọng, bộ lông dày và óng mượt. Sức khỏe đảm bảo, đã được tiêm phòng định kỳ. Thích hợp cho người yêu thích mèo kiểng quý phái.",
    variants: ["Golden nhạt", "Golden đậm"],
    features: [
      "Bộ lông dày, mềm mượt",
      "Sức khỏe đã kiểm định",
      "Rất thân thiện và dễ nuôi",
    ],
    tags: ["Mèo Anh", "Golden", "Sang trọng"],
  },
  {
    slug: "meo-aln-black-golden",
    name: "Mèo Anh lông ngắn màu Black Golden mã ALN3264",
    price: 490000,
    oldPrice: 590000,
    discount: 17,
    category_id: 1,
    stock: 4,
    rating: 5.0,
    reviews: 87,
    sold: 45,
    brand: "Luxury Pet Center",
    images: [
      "/images/meo/meo_anh_3.jpg",
      "/images/meo/meo_anh_3b.jpg",
      "/images/meo/meo_anh_3c.jpg",
    ],
    description:
      "Mèo Anh lông ngắn Black golden, giống thuần chủng 100%. Ngoại hình sang trọng, tính cách hiền lành, dễ nuôi. Được nhiều gia đình và người nổi tiếng yêu thích.",
    variants: ["Black Golden", "Black Silver"],
    features: [
      "Thuần chủng 100%",
      "Ngoại hình sang trọng",
      "Được nhiều nghệ sĩ tin chọn",
    ],
    tags: ["Mèo Anh lông ngắn", "Black Golden", "Thuần chủng"],
  },
  {
    slug: "meo-aln-silver-tabby",
    name: "Mèo Anh lông ngắn màu Silver Tabby ALN3263",
    price: 199000,
    oldPrice: 250000,
    discount: 20,
    category_id: 1,
    stock: 7,
    rating: 4.7,
    reviews: 33,
    sold: 18,
    brand: "Cat Lovers Club",
    images: [
      "/images/meo/meo_anh_4.jpg",
      "/images/meo/meo_anh_4b.jpg",
      "/images/meo/meo_anh_4c.jpg",
    ],
    description:
      "Mèo Anh lông ngắn Silver tabby độc đáo. Bộ lông mượt mà, ngoại hình nổi bật. Tính cách dễ chịu, thân thiện với trẻ nhỏ và người già, dễ chăm sóc.",
    variants: ["Silver Tabby nhạt", "Silver Tabby đậm"],
    features: [
      "Ngoại hình độc đáo",
      "Dễ chăm sóc",
      "Phù hợp nuôi trong căn hộ",
    ],
    tags: ["Silver Tabby", "Mèo cảnh", "Dễ nuôi"],
  },
  {
    slug: "meo-aln-bicolor",
    name: "Mèo Anh lông ngắn màu Bicolor mã ALN3259",
    price: 233000,
    oldPrice: 250000,
    discount: 7,
    category_id: 1,
    stock: 6,
    rating: 4.5,
    reviews: 25,
    sold: 27,
    brand: "Sweet Home Pet",
    images: [
      "/images/meo/meo_anh_5.jpg",
      "/images/meo/meo_anh_5b.jpg",
      "/images/meo/meo_anh_5c.jpg",
    ],
    description:
      "Mèo Anh lông ngắn Bicolor đáng yêu, khỏe mạnh. Ngoại hình dễ thương, hiền lành và thân thiện. Rất phù hợp nuôi làm thú cưng trong gia đình.",
    variants: ["Bicolor Trắng - Xám", "Bicolor Trắng - Vàng"],
    features: [
      "Dễ thương, hiền lành",
      "Phù hợp gia đình có trẻ nhỏ",
      "Khỏe mạnh, dễ nuôi",
    ],
    tags: ["Bicolor", "Mèo Anh", "Gia đình"],
  },

  // ⭐ Thêm 5 mèo mới ⭐
  {
    slug: "meo-scottish-fold-blue",
    name: "Mèo Scottish Fold tai cụp màu Blue",
    price: 410000,
    oldPrice: 480000,
    discount: 15,
    category_id: 1,
    stock: 4,
    rating: 4.9,
    reviews: 63,
    sold: 29,
    brand: "Blue Sky Cats",
    images: [
      "/images/meo/meo_anh_6.jpg",
      "/images/meo/meo_anh_6b.jpg",
      "/images/meo/meo_anh_6c.jpg",
    ],
    description:
      "Scottish Fold tai cụp màu Blue độc đáo, hiền lành và dễ thương. Bộ lông ngắn mượt mà, rất thích hợp sống trong căn hộ hiện đại.",
    variants: ["Đực", "Cái"],
    features: [
      "Tai cụp tự nhiên",
      "Rất thân thiện",
      "Thích hợp nuôi trong nhà",
    ],
    tags: ["Scottish Fold", "Tai cụp", "Mèo cảnh"],
  },
  {
    slug: "meo-bengal-hoa",
    name: "Mèo Bengal vằn hoa văn dã thú",
    price: 650000,
    oldPrice: 720000,
    discount: 10,
    category_id: 2,
    stock: 2,
    rating: 4.9,
    reviews: 54,
    sold: 17,
    brand: "Exotic Pet House",
    images: [
      "/images/meo/meo_anh_7.jpg",
      "/images/meo/meo_anh_7b.jpg",
      "/images/meo/meo_anh_7c.jpg",
    ],
    description:
      "Mèo Bengal với bộ lông vằn đặc trưng giống báo hoang dã, mạnh mẽ nhưng cũng rất thân thiện và thông minh.",
    variants: ["Đực", "Cái"],
    features: [
      "Ngoại hình hoang dã",
      "Rất thông minh",
      "Năng động, thích chơi đùa",
    ],
    tags: ["Bengal", "Hoang dã", "Thông minh"],
  },
  {
    slug: "meo-sphynx-trang",
    name: "Mèo Sphynx không lông màu Trắng",
    price: 880000,
    oldPrice: 1000000,
    discount: 12,
    category_id: 2,
    stock: 3,
    rating: 4.8,
    reviews: 39,
    sold: 14,
    brand: "Exotic Cat World",
    images: [
      "/images/meo/meo_anh_8.jpg",
      "/images/meo/meo_anh_8b.jpg",
      "/images/meo/meo_anh_8c.jpg",
    ],
    description:
      "Mèo Sphynx không lông độc đáo, cực kỳ hiền lành và thông minh. Là lựa chọn yêu thích của những người cá tính.",
    variants: ["Trắng", "Hồng nhạt"],
    features: [
      "Không lông, da mềm mịn",
      "Thân thiện, tình cảm",
      "Rất thông minh",
    ],
    tags: ["Sphynx", "Độc đáo", "Thông minh"],
  },
  {
    slug: "meo-ragdoll-xanh",
    name: "Mèo Ragdoll mắt xanh",
    price: 720000,
    oldPrice: 800000,
    discount: 10,
    category_id: 3,
    stock: 5,
    rating: 5.0,
    reviews: 72,
    sold: 33,
    brand: "Royal Cat World",
    images: [
      "/images/meo/meo_anh_9.jpg",
      "/images/meo/meo_anh_9b.jpg",
      "/images/meo/meo_anh_9c.jpg",
    ],
    description:
      "Mèo Ragdoll nổi tiếng với bộ lông dài mềm mịn và đôi mắt xanh tuyệt đẹp. Tính cách ngoan ngoãn, hiền lành, dễ huấn luyện.",
    variants: ["Đực", "Cái"],
    features: [
      "Mắt xanh long lanh",
      "Rất tình cảm",
      "Thích hợp gia đình có trẻ em",
    ],
    tags: ["Ragdoll", "Mèo kiểng", "Quý phái"],
  },
  {
    slug: "meo-maine-coon",
    name: "Mèo Maine Coon khổng lồ",
    price: 950000,
    oldPrice: 1100000,
    discount: 14,
    category_id: 3,
    stock: 2,
    rating: 5.0,
    reviews: 91,
    sold: 25,
    brand: "Giant Cat House",
    images: [
      "/images/meo/meo_anh_10.jpg",
      "/images/meo/meo_anh_10b.jpg",
      "/images/meo/meo_anh_10c.jpg",
    ],
    description:
      "Mèo Maine Coon – giống mèo lớn nhất thế giới. Ngoại hình oai vệ, tính cách hiền hòa, cực kỳ thân thiện và dễ gần.",
    variants: ["Nâu", "Xám bạc"],
    features: [
      "Kích thước lớn ấn tượng",
      "Ngoại hình sang trọng",
      "Thân thiện với trẻ em",
    ],
    tags: ["Maine Coon", "Khổng lồ", "Thân thiện"],
  },
];

export default products;
