#Server port
server.port= 8900

#Application name
spring.application.name= api-gateway

#Client registration options :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/accounts/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=product-catalog-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-CATALOG-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/catalog/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/catalog/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/shop/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/shop/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[3].id=product-recommendation-service
spring.cloud.gateway.routes[3].uri=lb://PRODUCT-RECOMMENDATION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/review/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/review/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[4].id=shipping-service
spring.cloud.gateway.routes[4].uri=lb://SHIPPING-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/shipping/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/shipping(?<segment>.*), /shipping${segment}

spring.cloud.gateway.routes[5].id=payment-service
spring.cloud.gateway.routes[5].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/payment/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/api/payment(?<segment>.*), /payment${segment}

spring.cloud.gateway.routes[6].id=menu-service
spring.cloud.gateway.routes[6].uri=lb://MENU-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/menu/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/api/menu/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[7].id=post-service
spring.cloud.gateway.routes[7].uri=lb://POST-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/post/**
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/api/post/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[8].id=banner-service
spring.cloud.gateway.routes[8].uri=lb://BANNER-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/banner/**
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/api/banner/(?<segment>.*), /${segment}

#SPRING SESSION PROPERTIES :
#-------------------------------
spring.session.store-type=none

# Global CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3001
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
# spring.session.redis.namespace=session
# spring.session.redis.flush-mode=on_save
# spring.redis.host=localhost
# spring.redis.port=6379
