// app/layout.js - ROOT LAYOUT ĐƠN GIẢN
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

import Chatbot from "../components/Chatbot/Chatbot";

export default function RootLayout({ children }) {
  return (
    <html lang="vi" className="scroll-smooth">
      <body className="bg-gray-50 text-gray-900 min-h-screen">
        {children}
        <Toaster position="top-right" />
        <Chatbot />
      </body>
    </html>
  );
}